react -> react-native: fix ESLint error `jsxBracketSameLine is deprecated` with not latest "prettier", and
the reason of not using latest "eslint" is to: fix ESLint `TypeError: Module.createRequire is not a function` when using nodejs v10.15.3