react -> react-native: fix nodejs 8.9.3 will let `npm run web` cause D:\proj\GCanvasRNExamples\node_modules\terser-webpack-plugin\node_modules\jest-worker\build\WorkerPool.js:25   } catch {           ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\proj\GCanvasRNExamples\node_modules\terser-webpack-plugin\node_modules\jest-worker\build\index.js:38:42)